tasks:
# just this directory is different from wildcard zzgosh  zz-_44-_y21-1106-1822
# seems make build will start dc up, which prebuild will just hang, now try only do dc build zz-_44-_y21-1106-1846
  - init: | 
      make deps
      docker-compose build
      docker-compose pull
      sudo chmod o+rwx . 
      sudo chmod -R o+rw *
    command: docker-compose up 
# split right so normal terminal can be seen  zz-_44-_y21-1107-0714
    openMode: split-right
# direct open preview   
ports:
  - port: 8041
    visibility: private
    onOpen: open-preview
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix
    - bmewburn.vscode-intelephense-client
    - tabnine.tabnine-vscode
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
    - alexcvzz.vscode-sqlite
    - humao.rest-client
    - pkief.material-icon-theme
