# ELASTIC - Search
PUT http://api.codelytv.localhost:8030/courses/{{id}}
Content-Type: application/json

{
  "query": {
    "term": {
      "name": "Pepe"
    }
  }
}

###
# ELASTIC - Search
POST localhost:9200/backoffice_courses/_search
Content-Type: application/json

###

