courses_put:
  path: /courses/{id}
  controller: CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesPutController
  methods:  [PUT]

latest_course_get:
  path: /courses/latest
  controller: CodelyTv\Apps\Mooc\Backend\Controller\LatestCourse\LatestCourseController
  methods: [GET]
