courses_get:
  path: /courses
  controller: CodelyTv\Apps\Backoffice\Backend\Controller\Courses\CoursesGetController
  defaults: { auth: false }
  methods:  [GET]

course_last:
  path: /last-course
  controller: CodelyTv\Apps\Backoffice\Backend\Controller\Courses\LastVideoController
  defaults: { auth: false }
  methods:  [GET]